[package]
authors = ["Without Boats <woboats@gmail.com>"]
description = "cargonauts - easy REST API in Rust"
license = "MIT OR Apache-2.0"
name = "cargonauts"
repository = "https://github.com/withoutboats/cargonauts"
version = "0.1.1"

[dependencies]
futures = "0.1.3"
itertools = "0.5.2"
serde = { git = "https://github.com/withoutboats/serde", branch = "serializeable_objects" }
serde_json = { git = "https://github.com/withoutboats/json", branch = "serializeable_objects" }
io-adapter = { git = "https://github.com/withoutboats/io-adapter", branch = "master" }
