[package]
authors = ["Without Boats <woboats@gmail.com>"]
name = "rigging"
version = "0.1.0"

[dependencies]
futures = "0.1.11"
mime = "0.2.3"

[dependencies.mainsail]
path = "../mainsail"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper"

[dependencies.tokio-service]
branch = "stream-middleware"
git = "https://github.com/withoutboats/tokio-service"
